// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/sentinel/event.proto

package sentinel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Top-level ECS-like event message
type SecurityEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                                                                                            // ECS: event.id
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                                                       // ECS: @timestamp
	Event         *EventMeta             `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`                                                                                                               // ECS: event.*
	Host          *HostMeta              `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`                                                                                                                 // ECS: host.*
	User          *UserMeta              `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`                                                                                                                 // ECS: user.*
	Source        *SourceMeta            `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`                                                                                                             // ECS: source.*
	Destination   *DestinationMeta       `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`                                                                                                   // ECS: destination.*
	Process       *ProcessMeta           `protobuf:"bytes,8,opt,name=process,proto3" json:"process,omitempty"`                                                                                                           // ECS: process.*
	File          *FileMeta              `protobuf:"bytes,9,opt,name=file,proto3" json:"file,omitempty"`                                                                                                                 // ECS: file.*
	CustomFields  map[string]string      `protobuf:"bytes,100,rep,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Flexible for future-proofing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityEvent) Reset() {
	*x = SecurityEvent{}
	mi := &file_proto_sentinel_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityEvent) ProtoMessage() {}

func (x *SecurityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityEvent.ProtoReflect.Descriptor instead.
func (*SecurityEvent) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_event_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SecurityEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SecurityEvent) GetEvent() *EventMeta {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SecurityEvent) GetHost() *HostMeta {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *SecurityEvent) GetUser() *UserMeta {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SecurityEvent) GetSource() *SourceMeta {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SecurityEvent) GetDestination() *DestinationMeta {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *SecurityEvent) GetProcess() *ProcessMeta {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *SecurityEvent) GetFile() *FileMeta {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *SecurityEvent) GetCustomFields() map[string]string {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

// Sub-messages
type EventMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      []string               `protobuf:"bytes,1,rep,name=category,proto3" json:"category,omitempty"` // ECS: event.category
	Type          []string               `protobuf:"bytes,2,rep,name=type,proto3" json:"type,omitempty"`         // ECS: event.type
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`     // ECS: event.action
	Outcome       string                 `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"`   // ECS: event.outcome
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"` // ECS: event.provider
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_proto_sentinel_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventMeta) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *EventMeta) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *EventMeta) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EventMeta) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *EventMeta) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type HostMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"` // ECS: host.hostname
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`             // ECS: host.id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMeta) Reset() {
	*x = HostMeta{}
	mi := &file_proto_sentinel_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMeta) ProtoMessage() {}

func (x *HostMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMeta.ProtoReflect.Descriptor instead.
func (*HostMeta) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_event_proto_rawDescGZIP(), []int{2}
}

func (x *HostMeta) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // ECS: user.name
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                      // ECS: user.id
	EffectiveId   string                 `protobuf:"bytes,3,opt,name=effective_id,json=effectiveId,proto3" json:"effective_id,omitempty"` // ECS: user.effective_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMeta) Reset() {
	*x = UserMeta{}
	mi := &file_proto_sentinel_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMeta) ProtoMessage() {}

func (x *UserMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMeta.ProtoReflect.Descriptor instead.
func (*UserMeta) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_event_proto_rawDescGZIP(), []int{3}
}

func (x *UserMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserMeta) GetEffectiveId() string {
	if x != nil {
		return x.EffectiveId
	}
	return ""
}

type SourceMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`      // ECS: source.ip
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // ECS: source.port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceMeta) Reset() {
	*x = SourceMeta{}
	mi := &file_proto_sentinel_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceMeta) ProtoMessage() {}

func (x *SourceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceMeta.ProtoReflect.Descriptor instead.
func (*SourceMeta) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_event_proto_rawDescGZIP(), []int{4}
}

func (x *SourceMeta) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SourceMeta) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type DestinationMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`      // ECS: destination.ip
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // ECS: destination.port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestinationMeta) Reset() {
	*x = DestinationMeta{}
	mi := &file_proto_sentinel_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestinationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationMeta) ProtoMessage() {}

func (x *DestinationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationMeta.ProtoReflect.Descriptor instead.
func (*DestinationMeta) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_event_proto_rawDescGZIP(), []int{5}
}

func (x *DestinationMeta) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DestinationMeta) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ProcessMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`             // ECS: process.name
	Executable    string                 `protobuf:"bytes,2,opt,name=executable,proto3" json:"executable,omitempty"` // ECS: process.executable
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`              // ECS: process.pid
	Ppid          int32                  `protobuf:"varint,4,opt,name=ppid,proto3" json:"ppid,omitempty"`            // ECS: process.ppid
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`             // ECS: process.args
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMeta) Reset() {
	*x = ProcessMeta{}
	mi := &file_proto_sentinel_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMeta) ProtoMessage() {}

func (x *ProcessMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMeta.ProtoReflect.Descriptor instead.
func (*ProcessMeta) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_event_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessMeta) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *ProcessMeta) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessMeta) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessMeta) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type FileMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`     // ECS: file.path
	Access        string                 `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"` // ECS: file.access
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_proto_sentinel_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_event_proto_rawDescGZIP(), []int{7}
}

func (x *FileMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMeta) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_proto_sentinel_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_event_proto_rawDescGZIP(), []int{8}
}

func (x *EventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sentinel_event_proto protoreflect.FileDescriptor

const file_proto_sentinel_event_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/sentinel/event.proto\x12\bsentinel\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x04\n" +
	"\rSecurityEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x05event\x18\x03 \x01(\v2\x13.sentinel.EventMetaR\x05event\x12&\n" +
	"\x04host\x18\x04 \x01(\v2\x12.sentinel.HostMetaR\x04host\x12&\n" +
	"\x04user\x18\x05 \x01(\v2\x12.sentinel.UserMetaR\x04user\x12,\n" +
	"\x06source\x18\x06 \x01(\v2\x14.sentinel.SourceMetaR\x06source\x12;\n" +
	"\vdestination\x18\a \x01(\v2\x19.sentinel.DestinationMetaR\vdestination\x12/\n" +
	"\aprocess\x18\b \x01(\v2\x15.sentinel.ProcessMetaR\aprocess\x12&\n" +
	"\x04file\x18\t \x01(\v2\x12.sentinel.FileMetaR\x04file\x12N\n" +
	"\rcustom_fields\x18d \x03(\v2).sentinel.SecurityEvent.CustomFieldsEntryR\fcustomFields\x1a?\n" +
	"\x11CustomFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\tEventMeta\x12\x1a\n" +
	"\bcategory\x18\x01 \x03(\tR\bcategory\x12\x12\n" +
	"\x04type\x18\x02 \x03(\tR\x04type\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\"6\n" +
	"\bHostMeta\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"Q\n" +
	"\bUserMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12!\n" +
	"\feffective_id\x18\x03 \x01(\tR\veffectiveId\"0\n" +
	"\n" +
	"SourceMeta\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"5\n" +
	"\x0fDestinationMeta\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"{\n" +
	"\vProcessMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"executable\x18\x02 \x01(\tR\n" +
	"executable\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x04 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\"6\n" +
	"\bFileMeta\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06access\x18\x02 \x01(\tR\x06access\")\n" +
	"\rEventResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2U\n" +
	"\rEventIngestor\x12D\n" +
	"\fStreamEvents\x12\x17.sentinel.SecurityEvent\x1a\x17.sentinel.EventResponse(\x010\x01B<Z:github.com/Boyul-Kim/pulsesentinel/proto/sentinel;sentinelb\x06proto3"

var (
	file_proto_sentinel_event_proto_rawDescOnce sync.Once
	file_proto_sentinel_event_proto_rawDescData []byte
)

func file_proto_sentinel_event_proto_rawDescGZIP() []byte {
	file_proto_sentinel_event_proto_rawDescOnce.Do(func() {
		file_proto_sentinel_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sentinel_event_proto_rawDesc), len(file_proto_sentinel_event_proto_rawDesc)))
	})
	return file_proto_sentinel_event_proto_rawDescData
}

var file_proto_sentinel_event_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_sentinel_event_proto_goTypes = []any{
	(*SecurityEvent)(nil),         // 0: sentinel.SecurityEvent
	(*EventMeta)(nil),             // 1: sentinel.EventMeta
	(*HostMeta)(nil),              // 2: sentinel.HostMeta
	(*UserMeta)(nil),              // 3: sentinel.UserMeta
	(*SourceMeta)(nil),            // 4: sentinel.SourceMeta
	(*DestinationMeta)(nil),       // 5: sentinel.DestinationMeta
	(*ProcessMeta)(nil),           // 6: sentinel.ProcessMeta
	(*FileMeta)(nil),              // 7: sentinel.FileMeta
	(*EventResponse)(nil),         // 8: sentinel.EventResponse
	nil,                           // 9: sentinel.SecurityEvent.CustomFieldsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_proto_sentinel_event_proto_depIdxs = []int32{
	10, // 0: sentinel.SecurityEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: sentinel.SecurityEvent.event:type_name -> sentinel.EventMeta
	2,  // 2: sentinel.SecurityEvent.host:type_name -> sentinel.HostMeta
	3,  // 3: sentinel.SecurityEvent.user:type_name -> sentinel.UserMeta
	4,  // 4: sentinel.SecurityEvent.source:type_name -> sentinel.SourceMeta
	5,  // 5: sentinel.SecurityEvent.destination:type_name -> sentinel.DestinationMeta
	6,  // 6: sentinel.SecurityEvent.process:type_name -> sentinel.ProcessMeta
	7,  // 7: sentinel.SecurityEvent.file:type_name -> sentinel.FileMeta
	9,  // 8: sentinel.SecurityEvent.custom_fields:type_name -> sentinel.SecurityEvent.CustomFieldsEntry
	0,  // 9: sentinel.EventIngestor.StreamEvents:input_type -> sentinel.SecurityEvent
	8,  // 10: sentinel.EventIngestor.StreamEvents:output_type -> sentinel.EventResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_sentinel_event_proto_init() }
func file_proto_sentinel_event_proto_init() {
	if File_proto_sentinel_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sentinel_event_proto_rawDesc), len(file_proto_sentinel_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sentinel_event_proto_goTypes,
		DependencyIndexes: file_proto_sentinel_event_proto_depIdxs,
		MessageInfos:      file_proto_sentinel_event_proto_msgTypes,
	}.Build()
	File_proto_sentinel_event_proto = out.File
	file_proto_sentinel_event_proto_goTypes = nil
	file_proto_sentinel_event_proto_depIdxs = nil
}
